project:
  type: website
  output-dir: ../docs

website:
  title: "Introduction to R"
  page-navigation: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics in R"
        contents:
          - href: syntax.qmd
          - href: gettinghelp.qmd
          - href: Rascalculator.qmd
          - href: objects.qmd
          - href: functions.qmd
          - href: yourfunction.qmd
          - href: subsetting.qmd
      - section: "Data visualization"
        contents:
          - href: plotBasics.qmd
          - href: boxplotsHistograms.qmd
          - href: colors.qmd
          - href: savingPlots.qmd
      - section: "Data analysis"
        contents:
          - href: tTests.qmd
          - href: corReg.qmd
          - href: anova.qmd
          - href: ordination.qmd
      - section: "Creating Maps in R"
        contents:
          - href: maps.qmd
          - href: occurrences.qmd
      - text: "Phylogenies in R"
        href: phylog.qmd
      - text: "Creating documents with R"
        href: quarto.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

